(define (domain multi_agent_box_pushing)
  (:requirements :strips :typing :equality)

  (:types
    agent location box bigbox
  )

  (:predicates
    (at ?a - agent ?l - location)
    (box-at ?b - box ?l - location)
    (bigbox-at ?b - bigbox ?l - location)
    (free ?l - location)

    (adjacent ?from ?to - location)
    (adj-up ?from ?to - location)
    (adj-down ?from ?to - location)
    (adj-left ?from ?to - location)
    (adj-right ?from ?to - location)
    (agent-occupies ?loc - location)
  )

  (:action move
    :parameters (?a - agent ?from - location ?to - location)
    :precondition (and
      (at ?a ?from)
      (adjacent ?from ?to)
      (free ?to)
    )
    :effect (and
      (not (at ?a ?from))
      (free ?from)
      (at ?a ?to)
      (agent-occupies ?to)
      (not (agent-occupies ?from))
    )
  )

  (:action push-small
    :parameters (?a - agent ?from - location ?boxloc - location ?toloc - location ?b - box)
    :precondition (and
      (at ?a ?from)
      (box-at ?b ?boxloc)
      (free ?toloc)
      (not (agent-occupies ?toloc))
      (or
        (and (adj-up ?from ?boxloc) (adj-up ?boxloc ?toloc))
        (and (adj-down ?from ?boxloc) (adj-down ?boxloc ?toloc))
        (and (adj-left ?from ?boxloc) (adj-left ?boxloc ?toloc))
        (and (adj-right ?from ?boxloc) (adj-right ?boxloc ?toloc))
      )
    )
    :effect (and
      (not (box-at ?b ?boxloc))
      (box-at ?b ?toloc)
      (free ?boxloc)
      (free ?from)
      (not (free ?toloc))
      (not (at ?a ?from))
      (at ?a ?boxloc)
      (agent-occupies ?boxloc)
    )
  )

  (:action push-big-up
    :parameters (?a1 ?a2 - agent ?from1 ?from2 ?boxloc1 ?boxloc2 ?toloc1 ?toloc2 - location ?b - bigbox)
    :precondition (and
      (at ?a1 ?from1)
      (at ?a2 ?from2)
      (not (= ?a1 ?a2))
      (= ?from1 ?from2)
      (= ?boxloc1 ?boxloc2)
      (= ?toloc1 ?toloc2)
      (bigbox-at ?b ?boxloc1)
      (adj-up ?from1 ?boxloc1)
      (adj-up ?boxloc1 ?toloc1)
      (free ?toloc1)
    )
    :effect (and
      (not (bigbox-at ?b ?boxloc1))
      (bigbox-at ?b ?toloc1)
      (free ?boxloc1)
      (not (free ?toloc1))
      (not (at ?a1 ?from1))
      (not (at ?a2 ?from2))
      (at ?a1 ?boxloc1)
      (at ?a2 ?boxloc1)
    )
  )

  (:action push-big-down
    :parameters (?a1 ?a2 - agent ?from1 ?from2 ?boxloc1 ?boxloc2 ?toloc1 ?toloc2 - location ?b - bigbox)
    :precondition (and
      (at ?a1 ?from1)
      (at ?a2 ?from2)
      (not (= ?a1 ?a2))
      (= ?from1 ?from2)
      (= ?boxloc1 ?boxloc2)
      (= ?toloc1 ?toloc2)
      (bigbox-at ?b ?boxloc1)
      (adj-down ?from1 ?boxloc1)
      (adj-down ?boxloc1 ?toloc1)
      (free ?toloc1)
    )
    :effect (and
      (not (bigbox-at ?b ?boxloc1))
      (bigbox-at ?b ?toloc1)
      (free ?boxloc1)
      (not (free ?toloc1))
      (not (at ?a1 ?from1))
      (not (at ?a2 ?from2))
      (free ?from1)
      (free ?from2)
      (at ?a1 ?boxloc1)
      (at ?a2 ?boxloc1)
    )
  )

  (:action push-big-left
    :parameters (?a1 ?a2 - agent ?from1 ?from2 ?boxloc1 ?boxloc2 ?toloc1 ?toloc2 - location ?b - bigbox)
    :precondition (and
      (at ?a1 ?from1)
      (at ?a2 ?from2)
      (not (= ?a1 ?a2))
      (= ?from1 ?from2)
      (= ?boxloc1 ?boxloc2)
      (= ?toloc1 ?toloc2)
      (bigbox-at ?b ?boxloc1)
      (adj-left ?from1 ?boxloc1)
      (adj-left ?boxloc1 ?toloc1)
      (free ?toloc1)
    )
    :effect (and
      (not (bigbox-at ?b ?boxloc1))
      (bigbox-at ?b ?toloc1)
      (free ?boxloc1)
      (not (free ?toloc1))
      (not (at ?a1 ?from1))
      (not (at ?a2 ?from2))
      (at ?a1 ?boxloc1)
      (at ?a2 ?boxloc1)
    )
  )

  (:action push-big-right
    :parameters (?a1 ?a2 - agent ?from1 ?from2 ?boxloc1 ?boxloc2 ?toloc1 ?toloc2 - location ?b - bigbox)
    :precondition (and
      (at ?a1 ?from1)
      (at ?a2 ?from2)
      (not (= ?a1 ?a2))
      (= ?from1 ?from2)
      (= ?boxloc1 ?boxloc2)
      (= ?toloc1 ?toloc2)
      (bigbox-at ?b ?boxloc1)
      (adj-right ?from1 ?boxloc1)
      (adj-right ?boxloc1 ?toloc1)
      (free ?toloc1)
    )
    :effect (and
      (not (bigbox-at ?b ?boxloc1))
      (bigbox-at ?b ?toloc1)
      (free ?boxloc1)
      (not (free ?toloc1))
      (not (at ?a1 ?from1))
      (not (at ?a2 ?from2))
      (at ?a1 ?boxloc1)
      (at ?a2 ?boxloc1)
    )
  )
)
