(define (domain box-push)
  (:requirements :strips :typing :equality)
  (:types agent location box heavybox)
  (:predicates
    (agent-at ?a - agent ?loc - location)
    (box-at ?b - box ?loc - location)
    (heavybox-at ?h - heavybox ?loc - location)
    (clear ?loc - location)
    (adj ?l1 - location ?l2 - location)
    (right-of ?from - location ?to - location)
    (left-of ?from - location ?to - location)
    (down-of ?from - location ?to - location)
    (up-of ?from - location ?to - location)
  )

  (:action move
    :parameters (?a - agent ?from - location ?to - location)
    :precondition (and
      (agent-at ?a ?from)
      (adj ?from ?to)
    )
    :effect (and
      (agent-at ?a ?to)
      (not (agent-at ?a ?from))
      (clear ?from)
    )
  )

  (:action push-small-right
    :parameters (?a - agent ?from - location ?boxloc - location ?toloc - location ?b - box)
    :precondition (and
      (agent-at ?a ?from)
      (right-of ?from ?boxloc)
      (right-of ?boxloc ?toloc)
      (box-at ?b ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a ?boxloc)
      (not (agent-at ?a ?from))
      (clear ?from)
      (box-at ?b ?toloc)
      (not (box-at ?b ?boxloc))
      (not (clear ?toloc))
    )
  )

  (:action push-small-left
    :parameters (?a - agent ?from - location ?boxloc - location ?toloc - location ?b - box)
    :precondition (and
      (agent-at ?a ?from)
      (left-of ?from ?boxloc)
      (left-of ?boxloc ?toloc)
      (box-at ?b ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a ?boxloc)
      (not (agent-at ?a ?from))
      (clear ?from)
      (box-at ?b ?toloc)
      (not (box-at ?b ?boxloc))
      (not (clear ?toloc))
    )
  )

  (:action push-small-down
    :parameters (?a - agent ?from - location ?boxloc - location ?toloc - location ?b - box)
    :precondition (and
      (agent-at ?a ?from)
      (down-of ?from ?boxloc)
      (down-of ?boxloc ?toloc)
      (box-at ?b ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a ?boxloc)
      (not (agent-at ?a ?from))
      (clear ?from)
      (box-at ?b ?toloc)
      (not (box-at ?b ?boxloc))
      (not (clear ?toloc))
    )
  )

  (:action push-small-up
    :parameters (?a - agent ?from - location ?boxloc - location ?toloc - location ?b - box)
    :precondition (and
      (agent-at ?a ?from)
      (up-of ?from ?boxloc)
      (up-of ?boxloc ?toloc)
      (box-at ?b ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a ?boxloc)
      (not (agent-at ?a ?from))
      (clear ?from)
      (box-at ?b ?toloc)
      (not (box-at ?b ?boxloc))
      (not (clear ?toloc))
    )
  )

  (:action push-heavy-right
    :parameters (?a1 - agent ?a2 - agent ?from - location ?boxloc - location ?toloc - location ?h - heavybox)
    :precondition (and
      (not (= ?a1 ?a2))
      (agent-at ?a1 ?from)
      (agent-at ?a2 ?from)
      (right-of ?from ?boxloc)
      (right-of ?boxloc ?toloc)
      (heavybox-at ?h ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a1 ?boxloc)
      (agent-at ?a2 ?boxloc)
      (not (agent-at ?a1 ?from))
      (not (agent-at ?a2 ?from))
      (clear ?from)
      (heavybox-at ?h ?toloc)
      (not (heavybox-at ?h ?boxloc))
      (not (clear ?toloc))
    )
  )

  (:action push-heavy-left
    :parameters (?a1 - agent ?a2 - agent ?from - location ?boxloc - location ?toloc - location ?h - heavybox)
    :precondition (and
      (not (= ?a1 ?a2))
      (agent-at ?a1 ?from)
      (agent-at ?a2 ?from)
      (left-of ?from ?boxloc)
      (left-of ?boxloc ?toloc)
      (heavybox-at ?h ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a1 ?boxloc)
      (agent-at ?a2 ?boxloc)
      (not (agent-at ?a1 ?from))
      (not (agent-at ?a2 ?from))
      (clear ?from)
      (heavybox-at ?h ?toloc)
      (not (heavybox-at ?h ?boxloc))
      (not (clear ?toloc))
    )
  )

  (:action push-heavy-down
    :parameters (?a1 - agent ?a2 - agent ?from - location ?boxloc - location ?toloc - location ?h - heavybox)
    :precondition (and
      (not (= ?a1 ?a2))
      (agent-at ?a1 ?from)
      (agent-at ?a2 ?from)
      (down-of ?from ?boxloc)
      (down-of ?boxloc ?toloc)
      (heavybox-at ?h ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a1 ?boxloc)
      (agent-at ?a2 ?boxloc)
      (not (agent-at ?a1 ?from))
      (not (agent-at ?a2 ?from))
      (clear ?from)
      (heavybox-at ?h ?toloc)
      (not (heavybox-at ?h ?boxloc))
      (not (clear ?toloc))
    )
  )

  (:action push-heavy-up
    :parameters (?a1 - agent ?a2 - agent ?from - location ?boxloc - location ?toloc - location ?h - heavybox)
    :precondition (and
      (not (= ?a1 ?a2))
      (agent-at ?a1 ?from)
      (agent-at ?a2 ?from)
      (up-of ?from ?boxloc)
      (up-of ?boxloc ?toloc)
      (heavybox-at ?h ?boxloc)
      (clear ?toloc)
    )
    :effect (and
      (agent-at ?a1 ?boxloc)
      (agent-at ?a2 ?boxloc)
      (not (agent-at ?a1 ?from))
      (not (agent-at ?a2 ?from))
      (clear ?from)
      (heavybox-at ?h ?toloc)
      (not (heavybox-at ?h ?boxloc))
      (not (clear ?toloc))
    )
  )
)
